.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH pisi 1  "pisi 3.0.0" 
.SH NAME
pisi\-rs \- Rust\-based Pisi Package Manager
.SH SYNOPSIS
\fBpisi\-rs\fR [\fB\-D\fR|\fB\-\-destdir\fR] [\fB\-y\fR|\fB\-\-yes\-all\fR] [\fB\-v\fR|\fB\-\-verbose\fR] [\fB\-d\fR|\fB\-\-debug\fR] [\fB\-N\fR|\fB\-\-no\-color\fR] [\fB\-L\fR|\fB\-\-bandwidth\-limit\fR] [\fB\-u\fR|\fB\-\-username\fR] [\fB\-p\fR|\fB\-\-password\fR] [\fB\-j\fR|\fB\-\-jobs\fR] [\fB\-\-download\-only\fR] [\fB\-\-ignore\-check\fR] [\fB\-\-log\-path\fR] [\fB\-\-opt\-level\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Rust\-based Pisi Package Manager
.SH OPTIONS
.TP
\fB\-D\fR, \fB\-\-destdir\fR \fI<DIR>\fR

.TP
\fB\-y\fR, \fB\-\-yes\-all\fR

.TP
\fB\-v\fR, \fB\-\-verbose\fR

.TP
\fB\-d\fR, \fB\-\-debug\fR

.TP
\fB\-N\fR, \fB\-\-no\-color\fR

.TP
\fB\-L\fR, \fB\-\-bandwidth\-limit\fR \fI<KILOBYTES>\fR

.TP
\fB\-u\fR, \fB\-\-username\fR \fI<USERNAME>\fR

.TP
\fB\-p\fR, \fB\-\-password\fR \fI<PASSWORD>\fR

.TP
\fB\-j\fR, \fB\-\-jobs\fR \fI<JOBS>\fR

.TP
\fB\-\-download\-only\fR

.TP
\fB\-\-ignore\-check\fR

.TP
\fB\-\-log\-path\fR \fI<FILE>\fR

.TP
\fB\-\-opt\-level\fR \fI<LEVEL>\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH SUBCOMMANDS
.TP
pisi\-rs\-add\-repo(1)
.TP
pisi\-rs\-blame(1)
.TP
pisi\-rs\-build(1)
.TP
pisi\-rs\-check\-install(1)
.TP
pisi\-rs\-check\-components(1)
.TP
pisi\-rs\-reset\-history(1)
.TP
pisi\-rs\-check\-repo(1)
.TP
pisi\-rs\-repo\-diff(1)
.TP
pisi\-rs\-toolchain(1)
.TP
pisi\-rs\-clean(1)
.TP
pisi\-rs\-configure\-pending(1)
.TP
pisi\-rs\-delete\-cache(1)
.TP
pisi\-rs\-delta(1)
.TP
pisi\-rs\-disable\-repo(1)
.TP
pisi\-rs\-emerge(1)
.TP
pisi\-rs\-emerge\-up(1)
.TP
pisi\-rs\-enable\-repo(1)
.TP
pisi\-rs\-fetch(1)
.TP
pisi\-rs\-graph(1)
.TP
pisi\-rs\-help(1)
.TP
pisi\-rs\-history(1)
.TP
pisi\-rs\-index(1)
.TP
pisi\-rs\-info(1)
.TP
pisi\-rs\-install(1)
.TP
pisi\-rs\-list\-available(1)
.TP
pisi\-rs\-list\-components(1)
.TP
pisi\-rs\-list\-files(1)
.TP
pisi\-rs\-list\-installed(1)
.TP
pisi\-rs\-list\-newest(1)
.TP
pisi\-rs\-list\-orphaned(1)
.TP
pisi\-rs\-list\-pending(1)
.TP
pisi\-rs\-list\-repo(1)
.TP
pisi\-rs\-list\-sources(1)
.TP
pisi\-rs\-list\-upgrades(1)
.TP
pisi\-rs\-rebuild\-db(1)
.TP
pisi\-rs\-remove(1)
.TP
pisi\-rs\-remove\-orphaned(1)
.TP
pisi\-rs\-remove\-repo(1)
.TP
pisi\-rs\-rollback(1)
.TP
pisi\-rs\-search(1)
.TP
pisi\-rs\-search\-file(1)
.TP
pisi\-rs\-update\-repo(1)
.TP
pisi\-rs\-upgrade(1)
.TP
pisi\-rs\-version(1)
.TP
pisi\-rs\-temp(1)
.SH VERSION
v3.0.0
