build build-host="localhost" \
      commonflags="-mtune=generic -march=x86-64 -O2 -pipe -fstack-protector -D_FORTIFY_SOURCE=2 -g -fPIC" \
      cflags="-mtune=generic -march=x86-64 -O2 -pipe -fstack-protector -D_FORTIFY_SOURCE=2 -g -fPIC" \
      cxxflags="-mtune=generic -march=x86-64 -O2 -pipe -fstack-protector -D_FORTIFY_SOURCE=2 -g -fPIC" \
      host="x86_64-pc-linux-gnu" \
      cc="x86_64-pc-linux-gnu-gcc" \
      cxx="x86_64-pc-linux-gnu-g++" \
      compressionlevel=9 \
      enablesandbox=true \
      fallback="http://source.pisilinux.org/1.0" \
      generatedebug=false \
      jobs="-j5" \
      ldflags="-Wl,-O1 -Wl,-z,relro -Wl,--hash-style=gnu -Wl,--as-needed -Wl,--sort-common" \
      ignored-build-types="pae"

directories cache-root-dir="/var/cache/pisi" \
            archives-dir="/var/cache/pisi/archives" \
            cached-packages-dir="/var/cache/pisi/packages" \
            compiled-packages-dir="/var/cache/pisi/packages" \
            debug-packages-dir="/var/cache/pisi/packages-debug" \
            lib-dir="/var/lib/pisi" \
            history-dir="/var/lib/pisi/history" \
            index-dir="/var/lib/pisi/index" \
            info-dir="/var/lib/pisi/info" \
            kde-dir="/usr" \
            lock-dir="/run/lock/subsys" \
            log-dir="/var/log" \
            packages-dir="/var/lib/pisi/package" \
            qt-dir="/usr" \
            tmp-dir="/var/pisi"

general architecture="x86_64" \
        autoclean=false \
        bandwidth-limit=0 \
        destination-directory="/" \
        distribution="PisiLinux" \
        distribution-release="2.0" \
        distribution-id="p2" \
        ignore-delta=false \
        ignore-safety=false \
        package-cache=true \
        package-cache-limit=0
