[package]
name = "pisi-builder"
version = "3.0.0"
edition = "2024"

[dependencies]
nix = { version = "0.27", features = ["sched", "mount", "user", "fs", "hostname"] }
duct = "0.13"
pisi-spec = { path = "../pisi-spec" }
pisi-core = { path = "../pisi-core" }
pyo3 = { version = "0.20", features = ["auto-initialize", "abi3-py38"] }

tar = "0.4"
xz2 = "0.1"
chrono = { version = "0.4", features = ["serde"] }
flate2 = "1.0"
indicatif = "0.17"
sha1 = "0.10.6"
rayon = "1.8"
zip = "0.6"
reqwest = { version = "0.11", features = ["blocking", "rustls-tls"], default-features = false }
quick-xml = { version = "0.31", features = ["serialize"] }
bzip2 = "0.4"
zstd = "0.13"
sha2 = "0.10"
md5 = "0.7"
rust-i18n = "3.1"
regex = "1"
glob = "0.3"
serde = { version = "1", features = ["derive"] }
kdl = "6"
